[Settings]
ID = "4ef59c2b-ba47-40ee-93a8-e3584f3770f0"

[build]
    base = "note-app/"

    publish = "note-app/build/"

    command = "yarn build"

[[redirects]]
    from = "/*"

    to = "/index.html"

    status = 200