[Settings]
ID = "4ef59c2b-ba47-40ee-93a8-e3584f3770f0"
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  
[build]
  # This is the directory to change to before starting a build.
  base    = "note-app"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "note-app/build/"
  # This will be your default build command
  command = "yarn build"
  [[redirects]]
    from = "/*"

    to = "/index.html"

    status = 200